// <auto-generated />
using System;
using HomeDoctor.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeDoctor.Data.Migrations
{
    [DbContext(typeof(HomeDoctorContext))]
    [Migration("20210407073921_updateDB-53")]
    partial class updateDB53
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ContractDisease", b =>
                {
                    b.Property<int>("ContractsContractId")
                        .HasColumnType("int");

                    b.Property<string>("DiseasesDiseaseId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ContractsContractId", "DiseasesDiseaseId");

                    b.HasIndex("DiseasesDiseaseId");

                    b.ToTable("ContractDisease");
                });

            modelBuilder.Entity("DiseaseHealthRecord", b =>
                {
                    b.Property<string>("DiseasesDiseaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HealthRecordsHealthRecordId")
                        .HasColumnType("int");

                    b.HasKey("DiseasesDiseaseId", "HealthRecordsHealthRecordId");

                    b.HasIndex("HealthRecordsHealthRecordId");

                    b.ToTable("DiseaseHealthRecord");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.ActionFirstTime", b =>
                {
                    b.Property<int>("ActionFirstTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AppointmentFirst")
                        .HasColumnType("bit");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PrescriptionFirst")
                        .HasColumnType("bit");

                    b.HasKey("ActionFirstTimeId");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("ActionFirstTime");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCanceled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExamination")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonCanceled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ContractId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AddressDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOBDoctor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOBPatient")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCancel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLocked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSigned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysOfTracking")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FullNameDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullNamePatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("NameLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumberDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PriceLicense")
                        .HasColumnType("real");

                    b.Property<string>("ReasonCancel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonLocked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkLocationDoctor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("PatientId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Disease", b =>
                {
                    b.Property<string>("DiseaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("End")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("Start")
                        .HasColumnType("int");

                    b.HasKey("DiseaseId");

                    b.ToTable("Disease");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.FireBaseFCM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("FireBaseFCM");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.HealthRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonalHealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasFilter("[ContractId] IS NOT NULL");

                    b.HasIndex("PersonalHealthRecordId");

                    b.ToTable("HealthRecord");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfExamination")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseId");

                    b.ToTable("License");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstruction", b =>
                {
                    b.Property<int>("MedicalInstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("MIShareFromId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalInstructionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VitalSignScheduleId")
                        .HasColumnType("int");

                    b.HasKey("MedicalInstructionId");

                    b.HasIndex("HealthRecordId");

                    b.HasIndex("MedicalInstructionTypeId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("VitalSignScheduleId");

                    b.ToTable("MedicalInstruction");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstructionImage", b =>
                {
                    b.Property<int>("MedicalInstructionImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicalInstructionId")
                        .HasColumnType("int");

                    b.HasKey("MedicalInstructionImageId");

                    b.HasIndex("MedicalInstructionId");

                    b.ToTable("MedicalInstructionImage");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstructionShare", b =>
                {
                    b.Property<int>("MedicalInstructionShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalInstructionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicalInstructionShareId");

                    b.HasIndex("ContractId");

                    b.HasIndex("MedicalInstructionId");

                    b.ToTable("MedicalInstructionShare");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstructionType", b =>
                {
                    b.Property<int>("MedicalInstructionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicalInstructionTypeId");

                    b.ToTable("MedicalInstructionType");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicationSchedule", b =>
                {
                    b.Property<int>("MedicationScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AfterNoon")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Morning")
                        .HasColumnType("int");

                    b.Property<int>("Night")
                        .HasColumnType("int");

                    b.Property<int>("Noon")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicationScheduleId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("MedicationSchedule");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountSendId")
                        .HasColumnType("int");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MedicalInstructionId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("OnSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("NotificationId");

                    b.HasIndex("AccountId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationType");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Career")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.PersonalHealthRecord", b =>
                {
                    b.Property<int>("PersonalHealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DateUpdateStatus")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyMedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalMedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SmartWatchConnected")
                        .HasColumnType("bit");

                    b.HasKey("PersonalHealthRecordId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PersonalHealthRecord");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DateCanceled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonCancel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Relative", b =>
                {
                    b.Property<int>("RelativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RelativeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Relative");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSign", b =>
                {
                    b.Property<int>("VitalSignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("MinuteAgain")
                        .HasColumnType("int");

                    b.Property<int?>("MinuteDangerInterval")
                        .HasColumnType("int");

                    b.Property<int?>("MinuteNormalInterval")
                        .HasColumnType("int");

                    b.Property<int?>("NumberMax")
                        .HasColumnType("int");

                    b.Property<int?>("NumberMin")
                        .HasColumnType("int");

                    b.Property<string>("TimeStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VitalSignScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("VitalSignTypeId")
                        .HasColumnType("int");

                    b.HasKey("VitalSignId");

                    b.HasIndex("VitalSignScheduleId");

                    b.HasIndex("VitalSignTypeId");

                    b.ToTable("VitalSign");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSignSchedule", b =>
                {
                    b.Property<int>("VitalSignScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("DateCanceled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VitalSignScheduleId");

                    b.ToTable("VitalSignSchedule");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSignType", b =>
                {
                    b.Property<int>("VitalSignTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("VitalSignName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VitalSignTypeId");

                    b.ToTable("VitalSignType");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSignValue", b =>
                {
                    b.Property<int>("VitalSignValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumberValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("TimeValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VitalSignTypeId")
                        .HasColumnType("int");

                    b.HasKey("VitalSignValueId");

                    b.HasIndex("PatientId");

                    b.HasIndex("VitalSignTypeId");

                    b.ToTable("VitalSignValue");
                });

            modelBuilder.Entity("ContractDisease", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractsContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiseaseHealthRecord", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseasesDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.HealthRecord", null)
                        .WithMany()
                        .HasForeignKey("HealthRecordsHealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Account", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.ActionFirstTime", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Contract", "Contract")
                        .WithOne("ActionFirstTime")
                        .HasForeignKey("HomeDoctor.Data.Models.ActionFirstTime", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Appointment", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Contract", "Contract")
                        .WithMany("Appointments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Contract", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId");

                    b.HasOne("HomeDoctor.Data.Models.Patient", "Patient")
                        .WithMany("Contracts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("License");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Doctor", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Account", "Account")
                        .WithOne("Doctor")
                        .HasForeignKey("HomeDoctor.Data.Models.Doctor", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.FireBaseFCM", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.HealthRecord", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Contract", "Contract")
                        .WithOne("HealthRecord")
                        .HasForeignKey("HomeDoctor.Data.Models.HealthRecord", "ContractId");

                    b.HasOne("HomeDoctor.Data.Models.PersonalHealthRecord", "PersonalHealthRecord")
                        .WithMany("HealthRecords")
                        .HasForeignKey("PersonalHealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("PersonalHealthRecord");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstruction", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.HealthRecord", "HealthRecord")
                        .WithMany("MedicalInstructions")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.MedicalInstructionType", "MedicalInstructionType")
                        .WithMany()
                        .HasForeignKey("MedicalInstructionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.Prescription", "Prescription")
                        .WithMany("MedicalInstructions")
                        .HasForeignKey("PrescriptionId");

                    b.HasOne("HomeDoctor.Data.Models.VitalSignSchedule", "VitalSignSchedule")
                        .WithMany("MedicalInstructions")
                        .HasForeignKey("VitalSignScheduleId");

                    b.Navigation("HealthRecord");

                    b.Navigation("MedicalInstructionType");

                    b.Navigation("Prescription");

                    b.Navigation("VitalSignSchedule");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstructionImage", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.MedicalInstruction", "MedicalInstruction")
                        .WithMany("MedicalInstructionImages")
                        .HasForeignKey("MedicalInstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalInstruction");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstructionShare", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Contract", "Contract")
                        .WithMany("MedicalInstructionShares")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.MedicalInstruction", "MedicalInstruction")
                        .WithMany("MedicalInstructionShares")
                        .HasForeignKey("MedicalInstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("MedicalInstruction");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicationSchedule", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Prescription", "Prescription")
                        .WithMany("MedicationSchedules")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Notification", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Patient", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Account", "Account")
                        .WithOne("Patient")
                        .HasForeignKey("HomeDoctor.Data.Models.Patient", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.PersonalHealthRecord", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Patient", "Patient")
                        .WithOne("PersonalHealthRecord")
                        .HasForeignKey("HomeDoctor.Data.Models.PersonalHealthRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Relative", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Patient", "Patient")
                        .WithMany("Relatives")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSign", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.VitalSignSchedule", "VitalSignSchedule")
                        .WithMany("VitalSigns")
                        .HasForeignKey("VitalSignScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.VitalSignType", "VitalSignType")
                        .WithMany()
                        .HasForeignKey("VitalSignTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VitalSignSchedule");

                    b.Navigation("VitalSignType");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSignValue", b =>
                {
                    b.HasOne("HomeDoctor.Data.Models.Patient", "Patient")
                        .WithMany("VitalSignValues")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeDoctor.Data.Models.VitalSignType", "VitalSignType")
                        .WithMany()
                        .HasForeignKey("VitalSignTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("VitalSignType");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Account", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Contract", b =>
                {
                    b.Navigation("ActionFirstTime");

                    b.Navigation("Appointments");

                    b.Navigation("HealthRecord");

                    b.Navigation("MedicalInstructionShares");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.HealthRecord", b =>
                {
                    b.Navigation("MedicalInstructions");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.MedicalInstruction", b =>
                {
                    b.Navigation("MedicalInstructionImages");

                    b.Navigation("MedicalInstructionShares");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Patient", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("PersonalHealthRecord");

                    b.Navigation("Relatives");

                    b.Navigation("VitalSignValues");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.PersonalHealthRecord", b =>
                {
                    b.Navigation("HealthRecords");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Prescription", b =>
                {
                    b.Navigation("MedicalInstructions");

                    b.Navigation("MedicationSchedules");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("HomeDoctor.Data.Models.VitalSignSchedule", b =>
                {
                    b.Navigation("MedicalInstructions");

                    b.Navigation("VitalSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
